# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09e3c670553a44050633c1f23fad329cf462cf027d69249cd76b1c6243c9b98d2f5baaadb968f802859614b9304ff1ca3121a951175ee1ef3f0bedded7d23dd4

test:
  secret_key_base: 629277f59b5523e2f9681dac6aecf2db6ba6303ff0874ea32c461d92c599796c8029907a77b0ff6129c6f201acb11038867703a8f81349a55454697272f05c89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
